package au.edu.sydney.elec5619.prac03.group8.nutrifit_app.dto.Response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Response DTO for AI meal estimation.
 * Contains estimated nutrition values and metadata.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AiMealEstimationResponseDTO {

    /**
     * ID of the saved meal (null if not saved)
     */
    private Long mealId;

    /**
     * URL of the uploaded image
     */
    private String photoUrl;

    /**
     * AI-generated or user-provided meal description
     */
    private String mealDescription;

    /**
     * Estimated total calories
     */
    private BigDecimal totalCalories;

    /**
     * Estimated protein in grams
     */
    private BigDecimal proteinG;

    /**
     * Estimated carbohydrates in grams
     */
    private BigDecimal carbsG;

    /**
     * Estimated fat in grams
     */
    private BigDecimal fatG;

    /**
     * Meal type (breakfast, lunch, dinner, snack)
     */
    private String role;

    /**
     * Whether this estimation was saved
     */
    private boolean saved;

    /**
     * Indicates this meal was generated by AI
     */
    private boolean aiGenerated;

    /**
     * Detailed nutrition summary (optional)
     */
    private MealNutritionSummaryDTO nutritionSummary;

    /**
     * Creates a response DTO from estimation data without saving
     */
    public static AiMealEstimationResponseDTO fromEstimation(
            String photoUrl,
            String description,
            BigDecimal calories,
            BigDecimal protein,
            BigDecimal carbs,
            BigDecimal fat,
            String role) {
        return AiMealEstimationResponseDTO.builder()
                .mealId(null)
                .photoUrl(photoUrl)
                .mealDescription(description)
                .totalCalories(calories)
                .proteinG(protein)
                .carbsG(carbs)
                .fatG(fat)
                .role(role)
                .saved(false)
                .aiGenerated(true)
                .build();
    }

    /**
     * Creates a response DTO from a saved meal
     */
    public static AiMealEstimationResponseDTO fromSavedMeal(
            Long mealId,
            String photoUrl,
            String description,
            BigDecimal calories,
            BigDecimal protein,
            BigDecimal carbs,
            BigDecimal fat,
            String role) {
        return AiMealEstimationResponseDTO.builder()
                .mealId(mealId)
                .photoUrl(photoUrl)
                .mealDescription(description)
                .totalCalories(calories)
                .proteinG(protein)
                .carbsG(carbs)
                .fatG(fat)
                .role(role)
                .saved(true)
                .aiGenerated(true)
                .build();
    }
}
